### ISSUE TITLE
Issue with the font

### ISSUE THREAD

**Issue by abdmurid** [silnrsi/font-alkalami#2]
Hi

First of all tribute for your work on this package. 

I am facing an issue as the following small example gives weird output. Could you pleas help on this ? 

**\documentclass{article}

\usepackage{arabluatex}
\usepackage[uthmani,nonumber]{quran}
 
\newfontfamily\arabicfont{Alkalami light}[Script=Arabic,Scale=2.06]

\begin{document}

\begin{txarab}
وَإِذَا المَوءۥدَةُ سُئِلَت
\end{txarab}

\end{document}**

Thank you so much !

Kindest regards

Alioune DIAGNE

**Comment by bobh0303** [comment]
It would be helpful if you would explain (a) what you expected should happen, and (b) what happened. If something doesn't look correct, please include graphics.

We did notice that your text includes U+06E5 ARABIC SMALL WAW which is not supported by the font, so that character is probably being rendered with a different font.

**Comment by abdmurid** [comment]
HI 

Thank you for your reply and and sorry for the incomplete description.

Yes the issue is about the small waw necessary is this coranic sentence. It is rendered this way what is not really expected :


Do you have any hint to get it properly rendered even in another font ?

Best regards

alioune

**Comment by bobh0303** [comment]
I still don't see any graphic in your reply. But I'll guess it is being rendered as 
![image](https://user-images.githubusercontent.com/6842108/87328910-73f8be80-c4f3-11ea-9733-ed9e073c9ef7.png) 
Can you confirm?

**Comment by abdmurid** [comment]
Yes I confirm. I don’t know why my screen shots don’t go neither in github nor in email. Sorry for that. I try once again

**Comment by LornaSIL** [comment]
I don't think we'll be updating Alkalami any time soon. I'm not really familiar with LuaTeX, but even if you can do a font substitution I would think it would look bad. One option would be to write a macro that converts U+06E5 to U+0648 and resize it small. That is all I can think of for you to do at the moment.

Since the font does not support any of the other quranic marks I suspect you will run into this issue for other characters. Alkalami was designed for modern orthographies.

**Comment by abdmurid** [comment]
Thank you.

**Comment by LornaSIL** [comment]
I've added this to our project as a character we may wish to consider adding in the future.

**Comment by abdmurid** [comment]
Good morning Lorna,

Great. Extending the character set would be excellent as it is one of the few with we call open-eyed letters (all letters have their internal parts clearly drawn) and we really need it for Quran in western Africa. 

Looking forward to hearing from your endeavour 

Kindest regards
